export const USER_LOGIN_REQUEST = 'AUTHENTICATION.USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'AUTHENTICATION.USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'AUTHENTICATION.USER_LOGIN_FAILURE';

export const USER_LOGOUT_SUCCESS = 'AUTHENTICATION.USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_REQUEST = 'AUTHENTICATION.USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAILURE = 'AUTHENTICATION.USER_LOGOUT_FAILURE';
