export const TOGGLE_FAVORITE = 'CONTENT.TOGGLE_FAVORITE';
export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';

export const MOVIES_REQUEST = 'CONTENT.MOVIES_REQUEST';
export const MOVIES_SUCCESS = 'CONTENT.MOVIES_SUCCESS';
export const MOVIES_FAILURE = 'CONTENT.MOVIES_FAILURE';

export const SINGLE_MOVIE_REQUEST = 'CONTENT.SINGLE_MOVIE_REQUEST';
export const SINGLE_MOVIE_SUCCESS = 'CONTENT.SINGLE_MOVIE_SUCCESS';
export const SINGLE_MOVIE_FAILURE = 'CONTENT.SINGLE_MOVIE_FAILURE';

export const GET_FAVORITE_MOVIES = 'CONTENT.GET_FAVORITE_MOVIES';

export const SAVE_MOVIE = 'CONTENT.GET_MOVIE';
