export const TOGGLE_FAVORITE = 'CONTENT.TOGGLE_FAVORITE';

export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';

export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';

export const MOVIES_REQUEST = 'CONTENT.MOVIES_REQUEST';
export const MOVIES_SUCCESS = 'CONTENT.MOVIES_SUCCESS';
export const MOVIES_FAILURE = 'CONTENT.MOVIES_FAILURE';

export const SAVE_MOVIE = 'CONTENT.GET_MOVIE';
