export const TOGGLE_FAVORITE = 'CONTENT.TOGGLE_FAVORITE';
export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';
export const SAVE_MOVIES = 'CONTENT.GET_MOVIES';
export const SAVE_MOVIE = 'CONTENT.GET_MOVIE';
